# Generated by Django 2.2.25 on 2022-01-07 03:21

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lattices',
            fields=[
                ('id_lattice', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('dimension', models.IntegerField()),
                ('determinant', models.FloatField()),
                ('minimal_norm', models.FloatField()),
                ('kissing_number', models.IntegerField()),
                ('gram_matrix', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=40), size=40)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
